// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9QoFHr2LMO6uOZl_0cNbGU3qwJx7bCaM',
    appId: '1:569072852264:web:677336e5235187abef041d',
    messagingSenderId: '569072852264',
    projectId: 'newclothes-e6fe1',
    authDomain: 'newclothes-e6fe1.firebaseapp.com',
    storageBucket: 'newclothes-e6fe1.firebasestorage.app',
    measurementId: 'G-ST5X5X1KPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-UwdXE7LtgukPm3HJV_PkPsagmr6Gzw',
    appId: '1:569072852264:android:4fea48e29cbdeae3ef041d',
    messagingSenderId: '569072852264',
    projectId: 'newclothes-e6fe1',
    storageBucket: 'newclothes-e6fe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQLiYfz5LfQVGHi3LGtZkRcKWRCYHzldw',
    appId: '1:569072852264:ios:c09ce895bcac1378ef041d',
    messagingSenderId: '569072852264',
    projectId: 'newclothes-e6fe1',
    storageBucket: 'newclothes-e6fe1.firebasestorage.app',
    iosBundleId: 'com.example.clothes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQLiYfz5LfQVGHi3LGtZkRcKWRCYHzldw',
    appId: '1:569072852264:ios:c09ce895bcac1378ef041d',
    messagingSenderId: '569072852264',
    projectId: 'newclothes-e6fe1',
    storageBucket: 'newclothes-e6fe1.firebasestorage.app',
    iosBundleId: 'com.example.clothes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9QoFHr2LMO6uOZl_0cNbGU3qwJx7bCaM',
    appId: '1:569072852264:web:5837d2c0593efbf7ef041d',
    messagingSenderId: '569072852264',
    projectId: 'newclothes-e6fe1',
    authDomain: 'newclothes-e6fe1.firebaseapp.com',
    storageBucket: 'newclothes-e6fe1.firebasestorage.app',
    measurementId: 'G-5ZQR15MMLC',
  );
}
